// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
public class InputWatcher
{
	public static KeyCode GrabOrDrop = KeyCode.E;
	public static KeyCode Activate = KeyCode.E;
	public static KeyCode Menu = KeyCode.Escape;

	public InputWatcher()
	{
	}
	// returns whether the user has pressed the jump key		
	public static bool IsJumping()
	{
		return Input.GetButtonDown("Jump");
	}
	// retruns the users current amount of horizontal input
	public static float horizontalInput()
	{
		return Input.GetAxisRaw("Horizontal");
	}
	// returns whether the user has pressed the activate key
	public static bool ActivateDown()
	{
		return Input.GetKeyDown(Activate);
	}
	// returns whether the user has pressed the grab/drop key
	public static bool GrabedOrDropDown()
	{
		return Input.GetKeyDown(GrabOrDrop);
	}
	// returns whether the user wants to open the menu
	public static bool OpenMenu()
	{
		return Input.GetKeyDown(Menu);
	}

	// returns to the users adjustment of the camera's scrolling
	public static float zoomDiff()
	{
		return Input.GetAxis("Mouse ScrollWheel");
	}
}

